policy: upsert-only

registry: txt
txtPrefix: "edns-"
txtOwnerId: "cloudflare"

extraArgs:
  - "--annotation-filter=dns.kian.sh/provider=cloudflare"
  - "--cloudflare-proxied"
  - "--default-targets=9a3deae9-8e4e-4017-93c1-474c61e52f19.cfargotunnel.com"
  - "--force-default-targets"

sources:
  - gateway-httproute

provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-external-dns
        key: CF_API_TOKEN
