policy: upsert-only

extraArgs:
  - "--pihole-api-version=6"

sources:
  - service
  - ingress
  - gateway-httproute

provider:
  name: pihole

env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-n3
        key: EXTERNAL_DNS_PIHOLE_PASSWORD
  - name: EXTERNAL_DNS_PIHOLE_SERVER
    valueFrom:
      secretKeyRef:
        name: pihole-n3
        key: EXTERNAL_DNS_PIHOLE_SERVER