apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: step-issuer-provisioner-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: password
    remoteRef:
      key: "848a1f42-c001-46b3-9aaa-b34000bb8283"