---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-admin-credentials
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mongodb-admin-credentials
  data:
    - secretKey: password
      remoteRef:
        key: "83476f3b-a8ff-4e4d-ac36-b4140041e71f"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-app-credentials
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mongodb-app-credentials
  data:
    - secretKey: password
      remoteRef:
        key: "0e7f0315-8143-4f96-9814-b4140041f6b9"
