---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-db-superuser
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: supabase-db-superuser
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "66fc2978-5764-40bc-98ea-b4160004c17b"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-db-credentials
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: supabase-db-credentials
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: supabase_admin
        password: "{{ .password }}"
        database: supabase
  data:
    - secretKey: password
      remoteRef:
        key: "9d6b6642-50a8-4857-8917-b4160004c1ca"
