---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-credentials
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mysql-credentials
    template:
      data:
        rootUser: root
        rootHost: "%"
        rootPassword: "{{ .rootPassword }}"
  data:
    - secretKey: rootPassword
      remoteRef:
        key: "1083a6ce-41e8-4858-bac9-b4140041e6c8"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-app-credentials
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mysql-app-credentials
    template:
      data:
        username: techgardencode
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "717de4c5-202f-4239-86d0-b4140041e6f0"
