---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql
  namespace: databases
spec:
  secretName: mysql-credentials
  tlsUseSelfSigned: true
  instances: 1
  podSpec:
    containers:
      - name: mysql
        resources:
          requests:
            cpu: 100m
            memory: 768Mi
          limits:
            memory: 1536Mi
  router:
    instances: 1
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    storageClassName: freenas-iscsi-ssd-csi
    resources:
      requests:
        storage: 10Gi
