apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://charts.jetstack.io
    name: cert-manager
    version: v1.18.2
    includeCRDs: true
    releaseName: cert-manager
    valuesFile: values.yaml
    namespace: cert-manager