image:
  repository: "ghcr.io/techgardencode/techgarden-blog"
  tag: "855d2664ad043df85f54834efe20ad9e2187cab8"
ports:
  - name: main
    containerPort: 8080
httpRoute:
  enabled: true
  hostname: blog.dev.techgarden.gg
envs:
  blog:
    PG_HOSTNAME: techgarden-db-rw.techgarden.svc
    PG_PORT: "5432"
    PG_DB: techgarden
    PG_USER: blog_write
    FLYWAY_USER: blog_flyway
    FLYWAY_SCHEMAS: blog
    APP_PROFILE_URL: http://techgarden-profile:8080
    KEYCLOAK_ISSUER_URI: https://sso.dev.techgarden.gg/realms/techgarden
    SPRING_JPA_HIBERNATE_DDL_AUTO: update
secretEnvs:
  blog:
    PG_PASSWORD: write-password
    FLYWAY_PASSWORD: flyway-password
    CLIENT_SECRET: CLIENT_SECRET
health:
  path: /actuator/health
