image:
  repository: "ghcr.io/techgardencode/techgarden-blog"
  tag: "cfca755560f1ba2eae3936a63c79f33fa25388c1"
ports:
  - name: main
    containerPort: 8080
service:
  type: LoadBalancer
ingress:
  annotations:
    cert-manager.io/issuer-group: certmanager.step.sm
    cert-manager.io/issuer-kind: StepClusterIssuer
    cert-manager.io/issuer: step-issuer
  host: blog.1276.internal.dev.techgarden.gg
  tls:
    secretName: blog.1276.internal.dev.techgarden.gg
envs:
  blog:
    PG_HOSTNAME: 10.0.60.80
    PG_PORT: "5432"
    PG_DB: postgres
    PG_USER: tg_blog
    KEYCLOAK_ISSUER_URI: https://sso.dev.techgarden.gg/realms/techgarden
secretEnvs:
  blog:
    PG_PASSWORD: PG_PASSWORD
health:
  path: /actuator/health
