image:
  repository: "ghcr.io/techgardencode/houseparty-ui"
  tag: "45c6b6e52d75daef467c2eb3a9ceb25a35e1c8d8"
health:
  path: /
ports:
  - name: main
    containerPort: 80
service:
  type: LoadBalancer
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: houseparty.techgarden.gg
  tls:
    secretName: houseparty-ui-techgarden-gg-tls
