image:
  repository: "ghcr.io/techgardencode/kian.coffee"
  tag: "latest@sha256:744664912d3831bc94cb39a972235691bb98c36d60186d12ec4d18ef7aee8f3e"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  public: true
  annotations:
    cert-manager.io/issuer-group: certmanager.step.sm
    cert-manager.io/issuer-kind: StepClusterIssuer
    cert-manager.io/issuer-name: step-issuer
  host: coffee.1276.internal.dev.techgarden.gg
  tls:
    secretName: coffee.1276.internal.dev.techgarden.gg