apiVersion: v1
kind: Service
metadata:
  name: keycloak-db-lb
  annotations:
    metallb.io/loadBalancerIPs: "10.0.61.141"
    dns.kian.sh/provider: internal
    external-dns.alpha.kubernetes.io/hostname: db.keycloak.dev.techgarden.gg
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/cluster: keycloak-db
    role: primary
