---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hausparty-db-superuser
  namespace: hausparty
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: hausparty-db-superuser
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "91b0a6ba-b486-4448-a9d7-b4240013d57c"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hausparty-db-app-credentials
  namespace: hausparty
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: hausparty-db-app-credentials
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: hausparty_app
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "c01f1185-d17d-4ade-a951-b4240013d5ac"
