existingSecrets:
  enabled: true
  ca: true
  certsAsSecret: true
  configAsSecret: true

service:
  type: LoadBalancer
  annotations:
    dns.kian.sh/provider: internal
    external-dns.alpha.kubernetes.io/hostname: ca.core.internal.kian.sh
    metallb.io/address-pool: system-pool
    metallb.io/loadBalancerIPs: 10.0.61.4

bootstrap:
  secrets: false
  enabled: false
  configmaps: false

ca:
  db:
    storageClass: freenas-iscsi-csi

inject:
  enabled: false