image:
  repository: "ghcr.io/techgardencode/techgarden-www"
  tag: "5c548bb5b2d84ae94b0b1effba3a1fe268322693"
ports:
  - name: main
    containerPort: 80
service:
  type: LoadBalancer
ingress:
  public: true
  annotations:
    cert-manager.io/issuer-group: certmanager.step.sm
    cert-manager.io/issuer-kind: StepClusterIssuer
    cert-manager.io/issuer: step-issuer
  host: www.1276.internal.dev.techgarden.gg
  tls:
    secretName: www.1276.internal.dev.techgarden.gg
