deploymentAnnotations:
  secret.reloader.stakater.com/reload: "bitwarden-tls-certs"

bitwarden-sdk-server:
  enabled: true
  namespaceOverride: platform
  deploymentAnnotations:
    secret.reloader.stakater.com/reload: "bitwarden-tls-certs"
