apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: postgres
  namespace: databases
spec:
  parentRefs:
    - name: eg-internal
      namespace: envoy-gateway-system
      sectionName: postgres
  rules:
    - backendRefs:
        - name: postgresql-rw
          port: 5432
