apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://mongodb.github.io/helm-charts
    name: community-operator
    version: 0.13.0
    includeCRDs: true
    releaseName: mongodb-operator
    namespace: mongodb
