image:
  repository: "ghcr.io/techgardencode/techgarden-www"
  tag: "3989dbe23ea4c839a72e86cb549604453b659016"
ports:
  - name: main
    containerPort: 80
service:
  type: ClusterIP
httpRoute:
  enabled: true
  hostname: www.techgarden.gg
gateway:
  public:
    enabled: true
