policy: upsert-only

extraArgs:
  - "--ingress-class=ingress-nginx-private"
  - "--pihole-api-version=6"

sources:
  - service
  - ingress
  - crd

provider:
  name: pihole

env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: EXTERNAL_DNS_PIHOLE_PASSWORD
  - name: EXTERNAL_DNS_PIHOLE_SERVER
    value: https://10.0.60.18