auth:
  existingSecret: keycloak
  passwordSecretKey: password
service:
  type: LoadBalancer
ingress:
  enabled: false
  hostname: sso.techgarden.gg
  ingressClassName: nginx-public
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    # cert-manager.io/issuer-group: certmanager.step.sm
    # cert-manager.io/issuer-kind: StepClusterIssuer
    # cert-manager.io/issuer: step-issuer
proxyHeaders: xforwarded
proxy: edge
postgresql:
  auth:
    existingSecret: keycloak
production: true
