---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kian-coffee
  namespace: kian-coffee
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: kian-coffee
  data:
    - secretKey: openpanel-client-id
      remoteRef:
        key: "bae84620-bcd2-4edc-9e97-b43600deac8e"
    - secretKey: glitchtip-dsn
      remoteRef:
        key: "f85f5151-d208-454b-9323-b43600deacb7"
