image:
  repository: "ghcr.io/techgardencode/kian.coffee"
  tag: "c203baf925f793399a25b8a2bebaf6f1a98b7c0a"
ports:
  - name: main
    containerPort: 80
service:
  type: LoadBalancer
ingress:
  public: true
  annotations:
    cert-manager.io/issuer-group: certmanager.step.sm
    cert-manager.io/issuer-kind: StepClusterIssuer
    cert-manager.io/issuer: step-issuer
  host: coffee.1501.internal.kian.sh
  tls:
    secretName: coffee.1501.internal.kian.sh
