---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dbgate-credentials
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: dbgate-credentials
  data:
    - secretKey: admin-password
      remoteRef:
        key: "1acc5c6b-5366-4b25-a8b3-b4140041f940"
