apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: "d4d8d92f-598d-42a2-8f0c-b33f0162c186"
