image:
  repository: "ghcr.io/techgardencode/kian-sh-docs"
  tag: "43c254cbe9350a3909f971b91b55476f7d54a6e5"
imagePullSecrets:
  - name: ghcr-credentials
ports:
  - name: main
    containerPort: 80
service:
  type: ClusterIP
health:
  enabled: true
  startupProbeSeconds: 60
  port: main
  type: HTTP
  path: /
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
httpRoute:
  enabled: true
  hostname: wiki.kian.sh
