tunnel: 9221faf4-41f8-4aa6-9cbc-1b757c2a2c07
credentials-file: /etc/cloudflared/credentials.json
no-autoupdate: true
ingress:
  # Tier 3: techgarden.gg apps via eg-public HTTPS
  - hostname: www.techgarden.gg
    service: https://10.0.62.3:443
    originRequest:
      originServerName: www.techgarden.gg
  - hostname: blog.techgarden.gg
    service: https://10.0.62.3:443
    originRequest:
      originServerName: blog.techgarden.gg
  - hostname: lizard.techgarden.gg
    service: https://10.0.62.3:443
    originRequest:
      originServerName: lizard.techgarden.gg
  - hostname: sso.techgarden.gg
    service: https://10.0.62.3:443
    originRequest:
      originServerName: sso.techgarden.gg
  # kian.coffee via eg-public HTTPS
  - hostname: kian.coffee
    service: https://10.0.62.3:443
    originRequest:
      originServerName: kian.coffee
  - hostname: www.kian.coffee
    service: https://10.0.62.3:443
    originRequest:
      originServerName: www.kian.coffee
  - service: http_status:404
