apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    tunnel: 9221faf4-41f8-4aa6-9cbc-1b757c2a2c07
    credentials-file: /etc/cloudflared/credentials.json
    no-autoupdate: true
    ingress:
      # Tier 3: techgarden.gg apps via eg-public HTTPS
      - hostname: www.techgarden.gg
        service: https://10.0.62.3:443
        originRequest:
          noTLSVerify: true
      - hostname: blog.techgarden.gg
        service: https://10.0.62.3:443
        originRequest:
          noTLSVerify: true
      - hostname: lizard.techgarden.gg
        service: https://10.0.62.3:443
        originRequest:
          noTLSVerify: true
      - hostname: sso.techgarden.gg
        service: https://10.0.62.3:443
        originRequest:
          noTLSVerify: false
          caPool: /etc/cloudflared/ca/ca.crt
      - service: http_status:404
