apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: techgarden-blog
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: write-password
      remoteRef:
        key: "51d7deb9-a9d5-456d-b7b3-b42200fd3bdb"
    - secretKey: flyway-password
      remoteRef:
        key: "4f911d77-5aa9-499c-b756-b42200fd3ba9"
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: "055e64a6-bcdf-4d49-b8e1-b36f011c1b5e"
