---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: keycloak-admin
    template:
      data:
        username: admin
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "b8c42734-7eaf-4b2a-a57f-b345017aaeff"
