---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: keycloak
data:
  techgarden-realm.json: |
    {
      "realm": "techgarden",
      "enabled": true,
      "registrationAllowed": false,
      "clients": [
        {
          "clientId": "bff",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "${KC_CLIENT_BFF_SECRET}",
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "redirectUris": ["*"],
          "webOrigins": ["*"],
          "defaultClientScopes": ["openid", "profile", "email", "offline_access"]
        },
        {
          "clientId": "svc.profile",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "${KC_CLIENT_PROFILE_SECRET}",
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": true
        }
      ]
    }
  hausparty-realm.json: |
    {
      "realm": "hausparty",
      "enabled": true,
      "registrationAllowed": false,
      "sslRequired": "all",
      "bruteForceProtected": true,
      "failureFactor": 5,
      "waitIncrementSeconds": 60,
      "maxFailureWaitSeconds": 900,
      "maxDeltaTimeSeconds": 43200,
      "roles": {
        "realm": [
          { "name": "site_admin", "description": "Hausparty site administrator" }
        ]
      },
      "clients": [
        {
          "clientId": "hausparty",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "${KC_CLIENT_HAUSPARTY_SECRET}",
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "redirectUris": ["https://hausparty.techgarden.gg/*"],
          "webOrigins": ["https://hausparty.techgarden.gg"],
          "defaultClientScopes": ["openid", "basic", "profile", "email"]
        }
      ]
    }
