auth:
  existingSecret: keycloak-secret
ingress:
  enabled: true
  hostname: sso.techgarden.gg
  ingressClassName: ingress-nginx-private
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
proxy: edge
postgresql:
  auth:
    secretKeys:
      userPasswordKey: postgres-password