image:
  debug: true
ingress:
  enabled: true
  hostname: sso.techgarden.gg
  ingressClassName: ingress-nginx-public
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
logging:
  level: DEBUG
postgresql:
  auth:
    existingSecret: keycloak-postgres-db
production: true
proxy: edge
