apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/externalsecret.yaml

helmCharts:
  - name: redis
    version: 0.27.1
    releaseName: redis
    repo: oci://registry-1.docker.io/cloudpirates
    valuesFile: values.yaml
