---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hausparty
  namespace: hausparty
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: hausparty
  data:
    - secretKey: anon-key
      remoteRef:
        key: "c4e09e22-aa4e-452f-a561-b4160004c2fe"
    - secretKey: service-role-key
      remoteRef:
        key: "342de8d9-8cf9-4abd-9e6f-b4160004c32c"
    - secretKey: admin-api-key
      remoteRef:
        key: "c5f03b67-e4d8-4888-99aa-b416000ff1b7"
    - secretKey: edmtrain-api-key
      remoteRef:
        key: "f336e797-bc78-4f2b-959e-b416000ff293"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: hausparty
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ghcr-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: "4f972fe7-8e8c-48d7-8bea-b41300df1574"
