image:
  repository: "ghcr.io/techgardencode/hausparty"
  tag: "d8917dc7c16956028f2cdc23744b00f21f766ba0"
imagePullSecrets:
  - name: ghcr-credentials
ports:
  - name: main
    containerPort: 3000
service:
  type: ClusterIP
health:
  enabled: true
  startupProbeSeconds: 60
  port: main
  type: HTTP
  path: /
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 256Mi
envs:
  - AUTH_KEYCLOAK_ID: "hausparty"
  - AUTH_KEYCLOAK_ISSUER: "https://sso.dev.techgarden.gg/realms/techgarden"
  - AUTH_URL: "https://hausparty.dev.techgarden.gg"
  - AUTH_TRUST_HOST: "true"
  - PG_HOSTNAME: "hausparty-db-rw.hausparty.svc.cluster.local"
  - PG_PORT: "5432"
  - PG_DB: "hausparty"
  - PG_USER: "hausparty_app"
secretEnvs:
  - AUTH_KEYCLOAK_SECRET: "keycloak-client-secret"
  - AUTH_SECRET: "auth-secret"
  - PG_PASSWORD: "pg-password"
  - ADMIN_API_KEY: "admin-api-key"
  - EDMTRAIN_API_KEY: "edmtrain-api-key"
httpRoute:
  enabled: true
  hostname: hausparty.dev.techgarden.gg
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hausparty.dev.techgarden.gg
