apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/externalsecret.yaml

helmCharts:
  - repo: https://kubernetes-sigs.github.io/external-dns
    name: external-dns
    version: 1.18.0
    releaseName: external-dns-private
    namespace: external-dns
    includeCRDs: true
    valuesFile: values.yaml