apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pelican
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: db-password
      remoteRef:
        key: "96b2534a-35c1-446f-8a88-b41b00161e94"
    - secretKey: app-key
      remoteRef:
        key: "153b942b-de41-4c94-9d48-b41b00161ed2"
    - secretKey: redis-password
      remoteRef:
        key: "1d7a1dc8-b9b3-4265-bdee-b41b0016204f"
