apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/externalsecret.yaml
  - base/functions-pvc.yaml

helmCharts:
  - name: supabase
    version: 0.5.3
    releaseName: supabase
    repo: https://supabase-community.github.io/supabase-kubernetes
    namespace: supabase
    valuesFile: values.yaml

patches:
  - path: base/studio-recreate-strategy-patch.yaml
    target:
      kind: Deployment
      name: supabase-supabase-studio
