---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: techgarden-db-superuser
  namespace: techgarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: techgarden-db-superuser
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "decc43c0-b6b2-469f-8e33-b42200fd3b48"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: techgarden-db-app-credentials
  namespace: techgarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: techgarden-db-app-credentials
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: techgardencode
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "851765de-269b-4c11-8cbb-b42200fd3b7c"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: techgarden-db-blog
  namespace: techgarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: flyway-password
      remoteRef:
        key: "4f911d77-5aa9-499c-b756-b42200fd3ba9"
    - secretKey: write-password
      remoteRef:
        key: "51d7deb9-a9d5-456d-b7b3-b42200fd3bdb"
    - secretKey: read-password
      remoteRef:
        key: "14f9c956-86ae-4180-9dca-b42200fd3c05"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: techgarden-db-profile
  namespace: techgarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: flyway-password
      remoteRef:
        key: "cde2899c-275a-4d51-8bcd-b42200fd4f2a"
    - secretKey: write-password
      remoteRef:
        key: "a3856dd4-2742-4eef-b04e-b42200fd51b9"
    - secretKey: read-password
      remoteRef:
        key: "4ddb5a48-dbb8-47ff-a654-b42200fd3c83"
