image:
  repository: "ghcr.io/techgardencode/kian.coffee"
  tag: "latest@sha256:744664912d3831bc94cb39a972235691bb98c36d60186d12ec4d18ef7aee8f3e"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  host: coffee.kian.sh
  tls:
    secretName: kian-coffee-tls
