---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secrets
  namespace: garage
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: garage-secrets
  data:
    - secretKey: rpc-secret
      remoteRef:
        key: "2d805f93-a9cb-4467-b098-b4850159c0d6"
    - secretKey: admin-token
      remoteRef:
        key: "aa3d4069-eaae-4c8c-b25b-b4850159c0fd"
