apiVersion: v1
kind: ConfigMap
metadata:
  name: step-ca-root-cert
  namespace: argocd
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXqgAwIBAgIRAPKgRARBA5kLUMcJovcBay4wCgYIKoZIzj0EAwIwSDEN
    MBwGA1UEChMVVGVjaEdhcmRlbiBQcml2YXRlIENBMSYwJAYDVQQDEx1UZWNoR2Fy
    ZGVuIFByaXZhdGUgQ0EgUm9vdCBDQTAeFw0yNTA4MTYxMzM5MDFaFw0zNTA4MTQx
    MzM5MDFaMEgxHjAcBgNVBAoTFVRlY2hHYXJkZW4gUHJpdmF0ZSBDQTEmMCQGA1UE
    AxMdVGVjaEdhcmRlbiBQcml2YXRlIENBIFJvb3QgQ0EwWTATBgcqhkjOPQIBBggq
    hkjOPQMBBwNCAASxMqpmHmrj+P4+tLgW70xByh895GFAB9Hs5sRPaGJREeEYVWLo
    /BfklnWDKNYCUhqccWf0wwXv4cejYZHtKrqIo0UwQzAOBgNVHQ8BAf8EBAMCAQYw
    EgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQULKqNahdcu+DRHjI01Sh3MM0r
    oVAwCgYIKoZIzj0EAwIDRwAwRAIgMrkl7AdjIcFQDoBPRCC2OlmzmWPjC/JrDWa+
    FLwXEs0CIDH1ef6p6nmkcmSE6Wlwm79M/lrZmQ5vNbU4nlns5QK/
    -----END CERTIFICATE-----
