---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: step-ca-pdb
  namespace: pki
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: step-certificates
