image:
  repository: "ghcr.io/techgardencode/sprout-ui"
  tag: "latest@sha256:534ff542729203a8f058c3dfb82b72da3090d68b56eacad8d35d0df61faccad3"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: sprout.techgarden.gg
  tls:
    secretName: sprout-techgarden-gg-tls
