image:
  repository: "ghcr.io/techgardencode/sprout-ui"
  tag: "latest@sha256:313c4b8d35fcbd9e183aa56a53dfcbe608d7d7148a2a588436f84a47ebe9a467"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: sprout.techgarden.gg
  tls:
    secretName: sprout-techgarden-gg-tls
