image:
  repository: "ghcr.io/techgardencode/sprout-ui"
  tag: "latest@sha256:db6ac09884bf4295e33c7a4f891568b9c8e1f8a09e8ed65538946545cf6022aa"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: sprout.techgarden.gg
  tls:
    secretName: sprout-techgarden-gg-tls
