image:
  repository: "ghcr.io/techgardencode/sprout-ui"
  tag: "latest@sha256:2c266df847f2b01f7b0b302e20a08efaf9d1819f492747f02242fca206c951d5"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: sprout.techgarden.gg
  tls:
    secretName: sprout-techgarden-gg-tls
