image:
  repository: "ghcr.io/techgardencode/sprout-ui"
  tag: "latest@sha256:907c7aca7488a377fe8124cd5b6972082db3a06041d2d2c6acc7b491d36a230e"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: sprout.techgarden.gg
  tls:
    secretName: sprout-techgarden-gg-tls
