image:
  repository: "ghcr.io/techgardencode/sprout-ui"
  tag: "latest@sha256:3153160dff66b0871e6adfffd9af22d65d4a9dd162037215ce67fa494f1cbaf3"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: sprout.techgarden.gg
  tls:
    secretName: sprout-techgarden-gg-tls
