---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-gaming-s3
  namespace: garage
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: garage-gaming-s3
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef: { key: "bde40c50-54c2-4724-a077-b485015c0272" }
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef: { key: "0f13329b-98b9-4c1a-ac9c-b485015c02a5" }
