apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-nfs-ssd-driver-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: driver-config-file.yaml
    remoteRef:
      key: "cb869a8b-8f5c-40f0-acb1-b41301085d59"
