---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openpanel-db-superuser
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: openpanel-db-superuser
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "35cb2dd0-1df9-4a6c-a191-b427015dcf1f"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openpanel-db-app-credentials
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: openpanel-db-app-credentials
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: openpanel
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "48590bff-c125-48ce-8547-b427015dcf7b"
