image:
  repository: "ghcr.io/techgardencode/techgarden-bff"
  tag: "7aa0667c50f5162436cb76daca67895d765a626c"
ports:
  - name: main
    containerPort: 8080
envs:
  - LOGGING_LEVEL_ROOT: debug
  - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: https://sso.dev.techgarden.gg/realms/techgarden
  - REDIS_HOST: redis.techgarden.svc.cluster.local
  - BFF_SERVICES_PROFILE: http://techgarden-profile:8080
  - KEYCLOAK_TOKEN_ENDPOINT: https://sso.dev.techgarden.gg/realms/techgarden/protocol/openid-connect/token
secretEnvs:
  bff:
    CLIENT_SECRET: CLIENT_SECRET
    REDIS_PASSWORD: REDIS_PASSWORD
health:
  path: /actuator/health
