image:
  repository: "ghcr.io/techgardencode/techgarden-bff"
  tag: "dd5e36130d2a64e9d85c700c98d6bd1c7105d174"
ports:
  - name: main
    containerPort: 8080
service:
  type: LoadBalancer
ingress:
  annotations:
    cert-manager.io/issuer-group: certmanager.step.sm
    cert-manager.io/issuer-kind: StepClusterIssuer
    cert-manager.io/issuer: step-issuer
  host: bff.1276.internal.dev.techgarden.gg
  tls:
    secretName: bff.1276.internal.dev.techgarden.gg
envs:
  - LOGGING_LEVEL_ROOT: debug
secretEnvs:
  bff:
    BFF_CLIENT_SECRET: BFF_CLIENT_SECRET
health:
  path: /actuator/health
