---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAJwu7gwvxY9hZx3mHlyyrPbFGkZIpmImvKCZNW0IvX5utnHLMhrLI37AAwrp+GoxeQ+TssQPBMYXY6oWMzNml+dHDCTEIaeXh9uQsDhmIbpgwoUvDbg9M9e7Q4pA7vdrDufTQA9wBxTO0+HGifYFQH+cSBATUB4Lm9Q6nnFccW2IncFGPjqDcTq6w5vUKandS8XpTwG4W1FPjjNiZJI/GJDgcjs+BWYXysfrxeRDGcd/KVkDFTHc53bUnAP1oWLMUH2Uc8qeK6WxHa2RNKk2GQCP3aJoEaVbHg6U6tfwgfUyJQdvuEja8j6+xxMeRQh5jXzH83A4Dbtl06AKrnaEwK0wAwEHlNcXlVLFJzMgGLFfiwlJ5iVV+zWQNLSlTXWxrTe33gwOq9IcdnzIjYakyZj1iJMStOaMOUuBdYrCuaK1gVdnkqQeU+IdfsAKodUbddOscPWCPNEUhaPHDK7Z3jeZLuOMot/oNMn5Tv3eOMgPcgNxhIw1UYpl9CyUZUgh04VAZ7bR176u7LpNLCPBENWVDYOZlcQeCc+USdi9N8eVlckrPT7wLOzLYksNEhFI27xa8q9mBUVThjp5ZNEqjxd7akO3EVu6s4jp80m51c+YVP6Nh5l8j36qMNxlh+vLCjXrlpOiHAui1KkoHyMSywEkbWWUNkRcPNfeU8X1eJhQMWGb3MkdhotS9YwKjhnLJELobSaI8UgkjieD5CSgW55Sti5Q5n6MZHf7byzpEpZz164FnTrF+r
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
