---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAzl1t8z7fI/Wp4dpYovtGrmBAFGSeWejAh0uiKtavJLkB3L9Lj/sYLexnfwpGGptsAcQDUd7pmagisSoSTcA8sc5/FFTr2tgGjwGTBsWp+alIItXcPa8kn1ivNi8iXb5hC5wCTEtG8QungWWQVl+ahpXDmHop4pwoU2F6XJ2uLcw80b+rDLrUos0IL5sNk7mvNA/IIq/NpCEoX6xQjwXY/m7Xug4wiOoapseFNnZsFzArRb6WHO9TbnO5YfvKOT9iZD5R0NPcsb7SfJkqXzuuGjjWbRi7jrbk8VPMcScF5fK5N78zchjdIoCrni/BIzHl8DDsnWPgDJNrGzJDxoqy/EZ4jMJESZTQvVSN1vKL8ndStWT2Tmab6ixThpHVtkMRS+TfTA8lFmbJv0HTAjZkmkIn1u7m00nMdU02yamY1n4q0XlEFZZxTnUl7HsUs9R+O0wlQL+RznHrymhcTTojeOZgaG3Auo2zFjBkF8Bkjr7uhIneGK+t3E/UdOQLmApMEqypsJ58kSxwdbN3xGa1/sYMKvGXYnyEq50+8xoJBgq7l+W4MicquvSyZwngyxkJJjWzHSTKDCTEfQ/MX5oeEl45Ow980MxtcnbFMsoQKO92ObYV2NgQsY9XQSEfXY1H/VCJ3k+1h48dyCMttN+aA/YKWVXBEXX09zIIySFZgh0NwS2JDLU5IokHv7LrvSslqQjPvgBm8x/Br1yFJJodhz7qOjkI36bWt2WBejAb5NbSQ+A5nan8X
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
