---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pihole-password
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCCKV+6Lq6JP0UVZz8nBjrKe/cBSbCUR1arwwP8jARsy8FyZ83wOsapkirlyfGyDup5dPGN8SbY+OlMpGxbyiGVtKH+hAY82TDukyoPCERaWs9M6hN/ovd5QIc35oT/TalH1eMrqCeIeMl3KXSBWLh/KLAaW+IWMwRATffeCaUMgzDUCiKamDQIoQ8vpx/ST4yl3neBYG/vpEBEGxxxZA6TJT2CX6yWZStVTyBVxFydMyWVThGrWNStq7+dxGvmMul5/lIFj31GQ/eG3lzYp1kWOs0fGR96jiAqRFtUah+O7m1O6WnO2LCZpru93v6R6HaH2P3lnAOXeKSLl77xuHfue70h6mal7Bd97mi1xOMz1MDtfVby6gW8anqiIueyiTFluAilANNXBCdCr+RVS7hRPjuM6LbwdxIb5oGNTfrkbYFMvV3o+TgJfTU1tp13OaJqBUeZ8eoDFnbnc3jwnMRt3PeyzsXc44bZLqhwA1p2OKu9dsx8D2wjfkmsOKBPaDpezqYR7J4P1bjJd7NOkv9iFuJSkrleVpuG7fPlWEQAJW78PoWLnzTMlzpzv1ZQvu/2KkruRe35rfdf0RZwS33ZyVWk9NfxCLT0+t4qpmyJjGvhuIGsDg3m517SLVjLmQBzdoQLnDShZR2KUgErh6KGydGFhZi0Zny7XprNijJwrYfWlejxzdO4HhVOnzFoW4rSOSeZxxCAlICzCRI7Bt6YCI2Fk2cClr761ZyrnbQFFLDt0l1aIMY0T0jC0g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pihole-password
      namespace: external-dns
