---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: step-ca-step-certificates-ca-password
  namespace: step-ca
spec:
  encryptedData:
    password: AgAZWLQG24d5awqs7Te0uplyQhtiz9xaUuUDdh3xrV/JffWUgs+H/4y78jiUNr8JTLFG4SGayzi1gM9xHhWY/e54qcu/cfLVesZUgxyrQrITXZmUu9LMTdu0TnyzYaWGBEwcvXsqFPAPjzW/0/kR9sHOL9sj/N9cWwpwZpZesOaCrKiK4JHw8q9Dnp3jgM3sTzbIV1DKzYqULEl+rsWJx4s2Erpo7+PMf+hJq2FSBAFlmLvOj/2CiEJ0N3Ues8HnCnGXCIONVxeEss9q+sHqP83hc6SahddcsDE9hFuP+ataF3rOHgqxbH410cMkQPOrKHHpbk6FOTO3xms3csVxxMhomNKQcOOIUGyucLyyM588mrNco6IikuK9W6KWz8vdVcIbV18lgceCupdgV0jqtiMXpBr8NXoT2c0JEFyfyh68R/fDQuHYRgPwFoLjQ8W6VaMBZG0UD0jS7PSln/r2YNQKHIunn9e7LFKk+Z5ZG10WniSWdpf9kuNYbdSHh0iVZ2Yh9RioA7KwLadNbrkMecktAQjyR0b+qgoUup8wFFj/7pIJOIY3YOKMJYxGsKx4RYCdLbpa5llCRFSkqqGa8nYD341PcXRbfqbjLbTfwGqQZnf9Ewh4cOx1x7b5WfXSKJgNu4tkcx1Bc8oLDKS9o69HgVo2hhesoqeo6NQ6YUVIWatvahmTxgTFubXHhy2rdD45BU61S1kAbL2eK1WyKm9X7keIIUCtENgc22Q+uOom4A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: step-ca-step-certificates-ca-password
      namespace: step-ca
    type: Opaque
