apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog

resources:
  - ../../base

helmCharts:
  - name: ghost
    version: 22.2.12
    releaseName: ghost
    repo: oci://registry-1.docker.io/bitnamicharts
    namespace: blog
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml
