apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resource-quota.yaml
  - limit-range.yaml
  - network-policy.yaml

helmGlobals:
  chartHome: ../../../../../helm-charts

helmCharts:
  - name: namespace
    releaseName: namespace
    valuesFile: values.yaml
