---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: databases-quota
  namespace: databases
spec:
  hard:
    requests.cpu: "4"
    limits.cpu: "8"
    requests.memory: 4Gi
    limits.memory: 10Gi
    persistentvolumeclaims: "10"
