---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-snapshots
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 5Gi
