apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - ../../base

helmCharts:
  - repo: https://kubernetes-sigs.github.io/external-dns
    name: external-dns
    version: 1.16.1
    releaseName: external-dns-private
    namespace: external-dns
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml
