cephClusterSpec:
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "10.0.60.70"
        devices:
          - name: "sdb"
      - name: "10.0.60.72"
        devices:
          - name: "sdb"
      - name: "10.0.60.74"
        devices:
          - name: "sdb"