---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hausparty
  namespace: hausparty
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: hausparty
  data:
    - secretKey: keycloak-client-secret
      remoteRef:
        key: "7efc9f22-9adb-4d03-86cb-b4240013d5d9"
    - secretKey: auth-secret
      remoteRef:
        key: "a110891d-6510-4a0d-a2d0-b4240013d606"
    - secretKey: pg-password
      remoteRef:
        key: "c01f1185-d17d-4ade-a951-b4240013d5ac"
    - secretKey: admin-api-key
      remoteRef:
        key: "29fde100-8411-49f6-821d-b4240013d632"
    - secretKey: edmtrain-api-key
      remoteRef:
        key: "ca35bc28-a18f-4eff-ab8e-b4240013de44"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: hausparty
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ghcr-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: "4f972fe7-8e8c-48d7-8bea-b41300df1574"
