image:
  repository: "ghcr.io/techgardencode/hausparty"
  tag: "3c22b94d362a664ccf1d0f6aab6ab6f8233dc08b"
imagePullSecrets:
  - name: ghcr-credentials
ports:
  - name: main
    containerPort: 3000
service:
  type: ClusterIP
health:
  enabled: true
  startupProbeSeconds: 60
  port: main
  type: HTTP
  path: /
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi
envs:
  - AUTH_KEYCLOAK_ID: "hausparty"
  - AUTH_KEYCLOAK_ISSUER: "https://sso.techgarden.gg/realms/hausparty"
  - AUTH_URL: "https://hausparty.techgarden.gg"
  - AUTH_TRUST_HOST: "true"
  - PG_HOSTNAME: "hausparty-db-rw.hausparty.svc.cluster.local"
  - PG_PORT: "5432"
  - PG_DB: "hausparty"
  - PG_USER: "hausparty_app"
secretEnvs:
  - AUTH_KEYCLOAK_SECRET: "keycloak-client-secret"
  - AUTH_SECRET: "auth-secret"
  - PG_PASSWORD: "pg-password"
  - ADMIN_API_KEY: "admin-api-key"
  - EDMTRAIN_API_KEY: "edmtrain-api-key"
httpRoute:
  enabled: true
  hostname: hausparty.techgarden.gg
gateway:
  public:
    enabled: true
    tunnelTarget: 9221faf4-41f8-4aa6-9cbc-1b757c2a2c07.cfargotunnel.com
