apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/externalsecret.yaml

helmGlobals:
  chartHome: ../../../../../helm-charts

helmCharts:
  - name: generic-service
    releaseName: techgarden-profile
    valuesFile: values.yaml