apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hausparty

resources:
  - edmtrain-upcoming-cronjob.yaml
  - edmtrain-festivals-cronjob.yaml
  - submission-drain-cronjob.yaml
  - sweep-stuck-runs-cronjob.yaml
  - scan-merge-candidates-cronjob.yaml
