csiDriver:
  name: "org.democratic-csi.nfs-ssd"

storageClasses:
  - name: freenas-nfs-ssd-csi
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

node:
  driver:
    extraEnv:
      - name: MOUNT_HOST_STRATEGY
        value: nsenter

driver:
  existingConfigSecret: democratic-csi-nfs-ssd-driver-config
  config:
    driver: freenas-nfs
