applicationsets:
  main:
    name: main
    generators:
      - git:
          repoURL: https://github.com/techgardencode/homelab.git
          revision: main
          directories:
            - path: "kubernetes/argocd/**/base"
            - path: "kubernetes/blog/**/base"
            - path: "kubernetes/default/**/base"
            - path: "kubernetes/external-dns/**/base"
            - path: "kubernetes/houseparty/**/base"
            - path: "kubernetes/ingress-nginx/**/base"
            - path: "kubernetes/cert-manager/**/base"
            - path: "kubernetes/monitoring/**/base"
            - path: "kubernetes/sealed-secrets/**/base"
            - path: "kubernetes/techgarden/**/base"
            - path: "kubernetes/tools/**/base"
    template:
      metadata:
        name: "{{path[1]}}-{{path[2]}}-{{path.basenameNormalized}}"
      spec:
        project: default
        source:
          repoURL: https://github.com/techgardencode/homelab.git
          targetRevision: main
          path: "{{path}}"
          plugin:
            name: kustomize-helm
            parameters:
              - name: NAMESPACE
                string: "{{path[1]}}"
        destination:
          name: in-cluster
          namespace: "{{path[1]}}"
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
            - ApplyOutOfSyncOnly=true
