---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kian-coffee
  namespace: kian-coffee
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: kian-coffee
  data:
    - secretKey: openpanel-client-id
      remoteRef:
        key: "52bb05ed-baa3-4a84-b118-b43600deac18"
    - secretKey: glitchtip-dsn
      remoteRef:
        key: "282fdf3c-1399-4184-8363-b43600deac6a"
