---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glitchtip-db-superuser
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: glitchtip-db-superuser
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "35cb2dd0-1df9-4a6c-a191-b427015dcf1f"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glitchtip-db-app-credentials
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: glitchtip-db-app-credentials
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: glitchtip
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "82cc5ab6-e31b-477c-bfa0-b427015dcf4a"
