image:
  repository: "ghcr.io/techgardencode/wiki"
  tag: "e7a89540f9cf3f473d4a6a3fa824dbfe2dec91cc"
imagePullSecrets:
  - name: ghcr-credentials
ports:
  - name: main
    containerPort: 80
service:
  type: ClusterIP
health:
  enabled: true
  startupProbeSeconds: 60
  port: main
  type: HTTP
  path: /
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
httpRoute:
  enabled: true
  hostname: wiki.kian.sh
