image:
  repository: "ghcr.io/techgardencode/kian-sh-docs"
  tag: "154b45b43542a3d159004cdb985542e7a69fa3ca"
imagePullSecrets:
  - name: ghcr-credentials
ports:
  - name: main
    containerPort: 80
service:
  type: ClusterIP
health:
  enabled: true
  startupProbeSeconds: 60
  port: main
  type: HTTP
  path: /
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
httpRoute:
  enabled: true
  hostname: wiki.kian.sh
