image:
  repository: "ghcr.io/techgardencode/wiki"
  tag: "2d5ea12742713ad1aa4fc654a9fd9c1b3c090978"
imagePullSecrets:
  - name: ghcr-credentials
ports:
  - name: main
    containerPort: 80
service:
  type: ClusterIP
health:
  enabled: true
  startupProbeSeconds: 60
  port: main
  type: HTTP
  path: /
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
httpRoute:
  enabled: true
  hostname: wiki.kian.sh
