apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://smallstep.github.io/helm-charts
    name: step-certificates
    version: v1.28.4
    releaseName: step-ca
    valuesFile: values.yaml
    namespace: step-ca