existingSecrets:
  enabled: true
  ca: true
  certsAsSecret: true
  configAsSecret: true

service:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ca.core.internal.techgarden.gg

bootstrap:
  secrets: false
  enabled: false
  configmaps: false

inject:
  enabled: false