apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technitium-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: TSIG_SECRET
      remoteRef:
        key: "06fac060-e9d4-42e1-86c7-b42400087462"
