auth:
  enabled: true
  existingSecret: redis
  existingSecretPasswordKey: password
persistence:
  enabled: false
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
