---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-realm-secrets
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: keycloak-realm-secrets
  data:
    - secretKey: bff-client-secret
      remoteRef:
        key: "fe4d0d45-b803-4142-8030-b34a01031268"
    - secretKey: profile-client-secret
      remoteRef:
        key: "5e2a956d-36f7-496a-8773-b3510162ad70"
    - secretKey: hausparty-client-secret
      remoteRef:
        key: "dfc135ab-56bd-42e6-83a8-b4230112ea1e"
