---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: keycloak
data:
  techgarden-realm.json: |
    {
      "realm": "techgarden",
      "enabled": true,
      "registrationAllowed": false,
      "clientScopes": [
        {
          "name": "api.hausparty",
          "protocol": "openid-connect",
          "protocolMappers": [
            {
              "name": "api.hausparty-audience",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "config": {
                "included.custom.audience": "api.hausparty",
                "access.token.claim": "true",
                "id.token.claim": "false"
              }
            }
          ]
        },
        {
          "name": "api.blog",
          "protocol": "openid-connect",
          "protocolMappers": [
            {
              "name": "api.blog-audience",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "config": {
                "included.custom.audience": "api.blog",
                "access.token.claim": "true",
                "id.token.claim": "false"
              }
            }
          ]
        },
        {
          "name": "api.profile",
          "protocol": "openid-connect",
          "protocolMappers": [
            {
              "name": "api.profile-audience",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "config": {
                "included.custom.audience": "api.profile",
                "access.token.claim": "true",
                "id.token.claim": "false"
              }
            }
          ]
        }
      ],
      "clients": [
        {
          "clientId": "hausparty",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "${KC_CLIENT_HAUSPARTY_SECRET}",
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "redirectUris": ["https://hausparty.dev.techgarden.gg/*"],
          "webOrigins": ["https://hausparty.dev.techgarden.gg"],
          "defaultClientScopes": ["openid", "basic", "profile", "email", "api.hausparty"]
        },
        {
          "clientId": "bff",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "${KC_CLIENT_BFF_SECRET}",
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "redirectUris": ["*"],
          "webOrigins": ["*"],
          "defaultClientScopes": ["openid", "basic", "profile", "email", "offline_access", "api.blog", "api.profile"]
        },
        {
          "clientId": "svc.profile",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "${KC_CLIENT_PROFILE_SECRET}",
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": true,
          "defaultClientScopes": ["openid", "basic", "api.blog", "api.profile"]
        }
      ]
    }
