apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://mysql.github.io/mysql-operator/
    name: mysql-operator
    version: 2.2.7
    includeCRDs: true
    releaseName: mysql-operator
    namespace: db-operators

patches:
  - target:
      kind: Deployment
      name: mysql-operator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
        value: 30
