---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: step-issuer-provisioner-password
  namespace: step-issuer
spec:
  encryptedData:
    password: AgA8JWKXRCLN7NA8VU4LNq6/9bWGTEtUaSXECrGYXVSHxfyzTQcj3I/rYGuuvHmw6wsistiIMR48PiljwszxzYneah0RIwsJpWROb4ZF0vWOEmpJq7poEtgvOq2hv2R389d2iN2x4pLnGV/obqYjNI36F1pNgtxVa94297tnEnEAzySCnuWL1BrTdnaMAllQ07wvPFrud5DjmSI1JxtTKwEdLwFcm19+kXfnyAjvprV8vqC+CULzEBfUGYAkhWv66oApalCJlZsCEwZ+YU2kimpBtiFtxMZp2rpOFRb36oakqaRBqvrqpDgP0J79yv18wPbP4z86719QRrRhxRRD9WOb3sslo/uvXzCCTyTJqfYtE0fu+Ls3mFVaW8r/rwJ2+7tnvkvsAPM4FI2vZ9ojkcTEDrTKrgfWSFHgAZft2u0nq499DeyPlNzy1sD7NNRpATe+ti8LMYdD8u1hsRj6MCuSVWydEUceSI8YusL6s2z1FHrwGB1bmQg7c3p5WRXHkB/kDgcD6QUWyE7M44kJxXQpCD8bFDnY0NaceZRpBREFv3yy5bhTERg83FdKYLvO7Uyz1uWNHPNIxMZnYGcvyeGVeNzi8HZaIY6b7zTB4sVwHwArl6L7uCpRKrJtgCXpel6P/n1GFrkQI6ud0id/0W3Dp9D3iH0R2l7fkAd7VeS3gjSZdq+qZfaIyDKTJYm/Nt5TINJZuJXtS13lPCvgNlgC1Zlk4OzXaVkWMXwU8snBAw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: step-issuer-provisioner-password
      namespace: step-issuer