---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-jwt
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: supabase-jwt
  data:
    - secretKey: secret
      remoteRef:
        key: "2e47de08-fbe5-4e3e-b2a6-b4160004c261"
    - secretKey: anon-key
      remoteRef:
        key: "c4e09e22-aa4e-452f-a561-b4160004c2fe"
    - secretKey: service-role-key
      remoteRef:
        key: "342de8d9-8cf9-4abd-9e6f-b4160004c32c"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-dashboard
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: supabase-dashboard
    template:
      data:
        username: supabase
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "5138ec81-15b0-4130-a5b5-b4160004c350"
