apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: houseparty

helmGlobals:
  chartHome: ../../../../../helm-charts

helmCharts:
  - name: generic-service
    releaseName: party-service
    valuesFile: ../../base/values.yaml
    namespace: houseparty
    additionalValuesFiles:
      - values.yaml
