---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-deploy-token
  namespace: wiki
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: github-deploy-token
  data:
    - secretKey: token
      remoteRef:
        key: "b8a8f2f1-4f25-492e-bb01-b41b0000cc1d"
