image:
  repository: "ghcr.io/techgardencode/kian-sh-docs"
  tag: "e26891f1e207b53e8b0446568e2ab64b38d888d2"
imagePullSecrets:
  - name: ghcr-credentials
ports:
  - name: main
    containerPort: 80
service:
  type: ClusterIP
health:
  enabled: true
  startupProbeSeconds: 60
  port: main
  type: HTTP
  path: /
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
httpRoute:
  enabled: true
  hostname: wiki.dev.kian.sh
