image:
  repository: "ghcr.io/techgardencode/kian-sh-docs"
  tag: "d05fa195577bf7145227df4541c1c4a0e5723402"
imagePullSecrets:
  - name: ghcr-credentials
ports:
  - name: main
    containerPort: 80
service:
  type: ClusterIP
health:
  enabled: true
  startupProbeSeconds: 60
  port: main
  type: HTTP
  path: /
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
httpRoute:
  enabled: true
  hostname: wiki.dev.kian.sh
