---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    apiKey: AgCohW3wum42q0blEdOBxtNtbCb8NS2eEZQ2GNwwAeyiHSqgurmw8xXHwyo14SFN72Sy8lgobXM6rr+fYUFzjun9FZzDxKpdlueY6DVPj0WfNJLsyx63ZoTUrk7hPG4IiYdDfDfS4dIsJrTSvC/yO2vkNxcPNuw8kCIxIDrCq0KAK0MkMd4OvQne9f0VIc3Qgog7COwZPoYw0w5oxO0O1hLYUjPr50GzZhIFEyq6OR+3PwHiL3+lySuYYG4VvjHa24xmoZoDXckmEa31Tatuseg8OA8+ebBJC9HrwPVOByqQb+bCRBjeyjVMAhk5g7wUOkIfOVTlBSlCCJMGmxZTMSKYHi50wo0TepSE6Hhj5/lTKlybzCXr4u0+lKMQlxoQ4LCn18ZFgrkFO5OEqlJIWBtNCfnQdPFRIR1/e1VOfE02+tQroHAFoNq3pngAmRh+uc1hSB5k8xbZobgSTU4uvC3nQfC4hnpIpvyEgXA0ueXKY8wcIJzZpAatuNqocu0vyMa7fPatq42Kl678Ziyy+hm6Noi7ICwv0eHDOlNFguKOYKoj/2cpBcmLOUI7xKdUY/n3cAScKmKrd+4NELTkUVIQSbNVbLbmvCbt8yB4cuSX5OBPPnq+nBYNCn3i5MSDbLjrefwcmNMPly+d4OBVmy8hM3H/3lbGdVRLzk9MtC3SlTV8GpVMzPwUvDy82Q0WlunI5kbhpBkg8oS9Ee4TfYfcTAAD2lH6GuAWXHE7YWETvEEzEAxOeqaa
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-api-key
      namespace: external-dns
