apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: loki
    version: 6.37.0
    releaseName: loki
    valuesFile: values.yaml
    namespace: monitoring