apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

helmGlobals:
  chartHome: ../../../../../helm-charts

helmCharts:
  - name: generic-service
    releaseName: techgarden-gg
    valuesFile: ../../base/values.yaml
    namespace: default
    additionalValuesFiles:
      - values.yaml
