---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pelican-db-superuser
  namespace: pelican
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: pelican-db-superuser
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "b15d5625-de0e-464d-9064-b485015f8982"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pelican-db-app-credentials
  namespace: pelican
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: pelican-db-app-credentials
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: pelican
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "d66f0284-6e67-4d07-9733-b485015f893c"
