policy: upsert-only

extraArgs:
  - "--pihole-api-version=6"
  - "--annotation-filter=external-dns.alpha.kubernetes.io/controller=internal"
  - "--txt-owner-id=homelab-internal"

sources:
  - service
  - ingress
  - gateway-httproute

provider:
  name: pihole

env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: technitium-dns
        key: EXTERNAL_DNS_PIHOLE_PASSWORD
  - name: EXTERNAL_DNS_PIHOLE_SERVER
    valueFrom:
      secretKeyRef:
        name: technitium-dns
        key: EXTERNAL_DNS_PIHOLE_SERVER
