image:
  repository: "ghcr.io/techgardencode/techgarden-profile"
  tag: "938fb895e6189eacbb94e5d7caf60fc3b6c64f84"
ports:
  - name: main
    containerPort: 8080
httpRoute:
  enabled: true
  hostname: profile.dev.techgarden.gg
envs:
  profile:
    PG_HOSTNAME: techgarden-db-rw.techgarden.svc
    PG_PORT: "5432"
    PG_DB: techgarden
    PG_USER: profile_write
    FLYWAY_USER: profile_flyway
    FLYWAY_SCHEMAS: profile
    APP_BLOG_URL: http://techgarden-blog:8080
    KEYCLOAK_ISSUER_URI: https://sso.dev.techgarden.gg/realms/techgarden
    SPRING_JPA_HIBERNATE_DDL_AUTO: update
secretEnvs:
  profile:
    PG_PASSWORD: write-password
    FLYWAY_PASSWORD: flyway-password
    CLIENT_SECRET: CLIENT_SECRET
health:
  path: /actuator/health
