apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - base/bitwarden-issuer.yaml
  - base/bitwarden-cert.yaml
  - base/secretstore.yaml
  - base/externalsecret.yaml

helmCharts:
  - repo: https://charts.external-secrets.io
    name: external-secrets
    version: v0.19.2
    releaseName: external-secrets
    valuesFile: values.yaml
    namespace: external-secrets