podAnnotations:
  secret.reloader.stakater.com/reload: "bitwarden-tls-certs"

bitwarden-sdk-server:
  enabled: true
  namespaceOverride: external-secrets
  podAnnotations:
    secret.reloader.stakater.com/reload: "bitwarden-tls-certs"