---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glitchtip-app-secrets
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: glitchtip-app-secrets
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secretKey }}"
        DATABASE_URL: "postgres://glitchtip:{{ .dbPassword }}@glitchtip-db-rw.observability.svc:5432/glitchtip"
  data:
    - secretKey: secretKey
      remoteRef:
        key: "7639bb8c-5ae8-4aeb-a0c6-b427015dcfa3"
    - secretKey: dbPassword
      remoteRef:
        key: "82cc5ab6-e31b-477c-bfa0-b427015dcf4a"
