image:
  repository: ghcr.io/pelican-dev/panel
  tag: "latest"

ports:
  - name: main
    containerPort: 80

service:
  type: ClusterIP

health:
  enabled: true
  startupProbeSeconds: 120
  path: /up
  type: HTTP

httpRoute:
  enabled: true
  hostname: pelican.techgarden.gg
gateway:
  public:
    enabled: true
    tunnelTarget: 9221faf4-41f8-4aa6-9cbc-1b757c2a2c07.cfargotunnel.com

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

database:
  enabled: false

envs:
  pelican:
    DB_CONNECTION: "mysql"
    DB_HOST: "mariadb"
    DB_PORT: "3306"
    DB_DATABASE: "pelican"
    DB_USERNAME: "pelican"
    CACHE_DRIVER: "redis"
    SESSION_DRIVER: "redis"
    QUEUE_CONNECTION: "redis"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
    APP_URL: "https://pelican.techgarden.gg"
    APP_TIMEZONE: "America/New_York"
    TRUSTED_PROXIES: "10.0.0.0/8"
    BEHIND_PROXY: "true"
    APP_ENV: "production"
    APP_INSTALLED: "true"

secretEnvs:
  pelican:
    DB_PASSWORD: db-password
    APP_KEY: app-key
    REDIS_PASSWORD: redis-password
