apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghost
spec:
  refreshInterval: 1h
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: db-password
    remoteRef:
      key: "e09f8a1d-464e-4141-82f1-b3410023a11a"
  - secretKey: user-password
    remoteRef:
      key: "ede39cfb-07e2-473a-be2e-b341002de0d4"