apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: MARIADB_ROOT_PASSWORD
      remoteRef:
        key: "96b2534a-35c1-446f-8a88-b41b00161e94"
    - secretKey: MARIADB_PASSWORD
      remoteRef:
        key: "96b2534a-35c1-446f-8a88-b41b00161e94"
