crds:
  enabled: true
  upgradeJob:
    enabled: true

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx-private
    annotations:
      cert-manager.io/issuer-group: certmanager.step.sm
      cert-manager.io/issuer-kind: StepClusterIssuer
      cert-manager.io/issuer: step-issuer
      external-dns.alpha.kubernetes.io/hostname: grafana.core.techgarden.gg
      external-dns.alpha.kubernetes.io/target: 10.0.60.56
      external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    hosts:
      - grafana.core.internal.techgarden.gg
    tls:
      - secretName: grafana.core.internal.techgarden.gg
        hosts:
          - grafana.core.internal.techgarden.gg
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx-private
    annotations:
      cert-manager.io/issuer-group: certmanager.step.sm
      cert-manager.io/issuer-kind: StepClusterIssuer
      cert-manager.io/issuer: step-issuer
      external-dns.alpha.kubernetes.io/hostname: prometheus.core.techgarden.gg
      external-dns.alpha.kubernetes.io/target: 10.0.60.56
      external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    hosts:
      - prometheus.core.internal.techgarden.gg
    tls:
      - secretName: prometheus.core.internal.techgarden.gg
        hosts:
          - prometheus.core.internal.techgarden.gg