---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: envoy-gateway-pdb
  namespace: envoy-gateway-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-helm
