apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: glitchtip
    version: 8.2.0
    releaseName: glitchtip
    repo: https://gitlab.com/api/v4/projects/glitchtip%2Fglitchtip-helm-chart/packages/helm/stable
    namespace: observability
    valuesFile: values.yaml

resources:
  - base/externalsecret.yaml
  - base/httproute.yaml
