---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-sql
  namespace: databases
data:
  01-create-roles.sql: |
    ALTER ROLE techgardencode CREATEDB CREATEROLE;
    CREATE ROLE readonly_role;
    GRANT CONNECT ON DATABASE techgarden TO readonly_role;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly_role;
  02-create-databases.sql: |
    CREATE DATABASE keycloak OWNER techgardencode;
