fullnameOverride: keycloak

image:
  repository: quay.io/keycloak/keycloak
  tag: "26.2"

command:
  - "/opt/keycloak/bin/kc.sh"
args:
  - "start"
  - "--import-realm"

replicas: 1

database:
  vendor: postgres
  hostname: keycloak-db-rw.keycloak.svc
  port: 5432
  database: keycloak
  username: keycloak
  existingSecret: keycloak-db-app-credentials
  existingSecretKey: password

proxy:
  enabled: true
  mode: xforwarded

http:
  relativePath: "/"

extraVolumes: |
  - name: realm-import
    configMap:
      name: keycloak-realm-config

extraVolumeMounts: |
  - name: realm-import
    mountPath: /opt/keycloak/data/import
    readOnly: true

extraEnv: |
  - name: KC_HOSTNAME
    value: sso.dev.techgarden.gg
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    valueFrom:
      secretKeyRef:
        name: keycloak-admin
        key: username
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-admin
        key: password
  - name: KC_CLIENT_BFF_SECRET
    valueFrom:
      secretKeyRef:
        name: keycloak-realm-secrets
        key: bff-client-secret
  - name: KC_CLIENT_PROFILE_SECRET
    valueFrom:
      secretKeyRef:
        name: keycloak-realm-secrets
        key: profile-client-secret
  - name: KC_CLIENT_HAUSPARTY_SECRET
    valueFrom:
      secretKeyRef:
        name: keycloak-realm-secrets
        key: hausparty-client-secret
  - name: KC_USER_TECHGARDENCODE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-realm-secrets
        key: user-techgardencode-password
  - name: KC_USER_TECHGARDENADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-realm-secrets
        key: user-techgardenadmin-password
  - name: KC_USER_TECHGARDENTEST_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-realm-secrets
        key: user-techgardentest-password

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    memory: 1Gi

ingress:
  enabled: false

dbchecker:
  enabled: true

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

podSecurityContext:
  fsGroup: 1000
