---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-db-credentials
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: supabase-db-credentials
    template:
      data:
        username: supabase_admin
        password: "{{ .password }}"
        database: supabase
  data:
    - secretKey: password
      remoteRef:
        key: "9d6b6642-50a8-4857-8917-b4160004c1ca"
