apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-tls-dev-techgarden
  namespace: envoy-gateway-system
spec:
  secretName: eg-tls-dev-techgarden
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "dev.techgarden.gg"
    - "*.dev.techgarden.gg"
