apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: techgarden-profile
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: write-password
      remoteRef:
        key: "a3856dd4-2742-4eef-b04e-b42200fd51b9"
    - secretKey: flyway-password
      remoteRef:
        key: "cde2899c-275a-4d51-8bcd-b42200fd4f2a"
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: "5e2a956d-36f7-496a-8773-b3510162ad70"
