---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hausparty-db-superuser
  namespace: hausparty
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: hausparty-db-superuser
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "0f3e7a33-90eb-4839-9339-b4230112e9d2"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hausparty-db-app-credentials
  namespace: hausparty
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: hausparty-db-app-credentials
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: hausparty_app
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "c75e6775-a630-4213-9086-b4230112e9f8"
