resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi

collectors:
  - pods
  - deployments
  - statefulsets
  - daemonsets
  - jobs
  - cronjobs
  - nodes
  - persistentvolumeclaims
  - namespaces
