---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pihole-password
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAtMDnUqGmHeb4T6T6jUQfSaiTz/ErMpt4588sk1fC+KxIueFgwwldz6sRYoKcy+n/0jHd3eNF/s/asSRjgeDc4OF+2HAJUzxrbXl4lfnXYeU9ismoTnoOoLPAJ6q71BPMOlwbb7R9J3SD1FNf2Da2Q5u/yGdJu1tldi7oD/Ifx6D1hdiFSnh2iz09E9wMrpjwvjrK0gtzVA2o4x+ryjHp8HufhSUIeeslbV1hMBz140vzsHL3Avr9NKzZZlXriTvEv7A8fAM+Y/fw+fsn21t2mSS/Q4D0LZaCYd8RBDDHbD1hKLqTrpKmojusxrd3shYWbVCd7kjv/t3NK8P/i45RvlHjDm/K+S1Vw++k2v9OzHbV2HBNY3qZ8SJEkx3PZTUChrNQk8/khar1GOcmw9Oe5fqQKlE7oPZQo+Q6one4gRd2wpKQ5lsVm30SOFm2xDWN3wvdTZvEvYU8xxEoe2PoqbZ/RrWip5QSsVh7TTtNqg2GAXyGiz6dYMwQfoOF/qHtUge6kzG9qe40lWHqMslAL0FvfWDt57xR9XZpcvGMIZKcVXfYZh8Hd8n4vwcqLI49Bz5Mf2t/Gpormne/meFndX3oqSCP9mPb0Ztljur9/U1KQSomGen4rV7LVbWiSJKxBX44P+oFT5/zEZso9VQvtftUsWOiNkOvjvpfmcD+MNBmUuusjHV2tA4b/yICuoemuTrHfLrT1KH0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pihole-password
      namespace: external-dns
