---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pihole-password
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCHheizAcVO/HoY8XY2eNuuo6Y4BLI7BOMFcC/dDGkN5PjZSpEjnrPnTcCxnOudj8ZbofpQokwq7sK5AG8cmMKxbv3ewh0VZaGJVjbk/v5J7xGIu7tCtn9+k24jkuYwCcDw5WJgl1h9OLtuak5XIi7oWGZleYJJMlPPnagGAcyOhKJVkv5ryR11doLtcUd+xydCwGpAbO6byB6ywuhsJs5lXGjMVUI/tlIzgdc+GIqD4T3i83u2q6An6MeDH+ikdR00y9Uew5cN2AhKJtx28UylAl1h9Nm8mpEgvykrCxXNRVTAHoG324GPcmfh/qw4fnR0mDrXsv2G2HnRqwfjRjcbjWZcu/Yt/nPvRJu2t9nyWj4pZ5rHTEzPrmCQsGCW+A4PQaKFhu3B7pkphfoudG2zbOP3+IQmbGHXjk+3V1hZHYxhk7LciTvdMvdXGA/G+08QN08GQOKdrntjGfTeHT3qV/CfZFuYYrpb2QCRSCg235Qd12Pwarbd6XMcSmEC/zuqdhpNufMVUqfszEOrz80Iq7c9czfHTEMFT+juGa86mRsHP+lDnohCluYwEgcX7Ty8ia9rULr6eAA7Tmtpi1D/OLvfHvkMq9Vs4wacUde3YEmgotYknq8VUO+qvgXSLorXWJZmqbtcTzrPcaI8BH9jL0hLbP1Gq478svGs3BkQcYQ9HFuEfRjpdECVMI4dmGzIamZjsuAJC9c=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pihole-password
      namespace: external-dns
    type: Opaque
