---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: databases
spec:
  instances: 1

  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-superuser

  postgresql:
    pg_hba:
      - host all postgres all scram-sha-256
      - host all all all scram-sha-256

  storage:
    size: 10Gi
    storageClass: freenas-iscsi-ssd-csi

  bootstrap:
    initdb:
      database: techgarden
      owner: techgardencode
      secret:
        name: postgresql-app-credentials
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: postgresql-init-sql
            key: 01-create-roles.sql

  monitoring:
    enablePodMonitor: false
    disableDefaultQueries: false

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
