---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-superuser
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: postgresql-superuser
    template:
      metadata:
        labels:
          cnpg.io/reload: ""
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "b71e8fe7-f109-44e8-820d-b4140041e679"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-app-credentials
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: postgresql-app-credentials
    template:
      metadata:
        labels:
          cnpg.io/reload: ""
      data:
        username: techgardencode
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "352bfb54-b879-4474-aded-b4140041e6a1"
