---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-sql
  namespace: databases
data:
  01-create-roles.sql: |
    CREATE ROLE readonly_role;
    GRANT CONNECT ON DATABASE appdb TO readonly_role;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly_role;
