image:
  repository: "ghcr.io/techgardencode/lizard"
  tag: "5b86e5fd6e11f532f269ae9aa1338718d74a3b6f"
ports:
  - name: main
    containerPort: 80
service:
  type: LoadBalancer
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: lizard.techgarden.gg
  tls:
    secretName: lizard-techgarden-gg-tls
