image:
  repository: "ghcr.io/techgardencode/hp_party-service"
  tag: "77410ba391328ff02804e4c3f562235667daefda"
health:
  path: /actuator/health
ports:
  - name: main
    containerPort: 8000
service:
  type: LoadBalancer
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: party.api.houseparty.techgarden.gg
  tls:
    secretName: party-service-techgarden-gg-tls
