image:
  repository: "ghcr.io/techgardencode/hp_party-service"
  tag: "d5da17507b05a2da21dfc86784034bfa9582d499"
health:
  path: /actuator/health
ports:
  - name: main
    containerPort: 8000
service:
  type: LoadBalancer
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: party.api.houseparty.techgarden.gg
  tls:
    secretName: party-service-techgarden-gg-tls
