apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://cloudnative-pg.github.io/charts
    name: cloudnative-pg
    version: 0.28.0
    includeCRDs: true
    releaseName: cnpg
    namespace: db-operators
