image:
  repository: "ghcr.io/techgardencode/kian.coffee"
  tag: "90239740af13080250faef0af3f903f7ab4a4078"
ports:
  - name: main
    containerPort: 80
service:
  type: ClusterIP
# Exposure: Tier 3 (Cloudflare Tunnel) + Internal
httpRoute:
  enabled: true
  hostname: kian.coffee
gateway:
  internal:
    enabled: true
  public:
    enabled: true
    tunnelTarget: 9221faf4-41f8-4aa6-9cbc-1b757c2a2c07.cfargotunnel.com
