image:
  repository: "ghcr.io/techgardencode/kian.coffee"
  tag: "29fbf8426b58f3d33f5fa2e8abdeb86c201a55b6"
ports:
  - name: main
    containerPort: 80
service:
  type: ClusterIP
# Exposure: Tier 3 (Cloudflare Tunnel) + Internal
httpRoute:
  enabled: true
  hostname: kian.coffee
gateway:
  internal:
    enabled: true
  public:
    enabled: true
    tunnelTarget: 9221faf4-41f8-4aa6-9cbc-1b757c2a2c07.cfargotunnel.com
