apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - ../../base

helmCharts:
  - repo: https://charts.jetstack.io
    name: cert-manager
    version: v1.18.2
    includeCRDs: true
    releaseName: cert-manager
    valuesFile: ../../base/values.yaml
    namespace: cert-manager
