apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: techgarden-bff
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: "fe4d0d45-b803-4142-8030-b34a01031268"
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: "5875ba53-da80-43ce-88c7-b345017a938d"
