policy: upsert-only

registry: txt
txtPrefix: "edns-"
txtOwnerId: "cloudflare"

extraArgs:
  - "--annotation-filter=dns.kian.sh/provider=cloudflare"
  - "--cloudflare-proxied"
  - "--default-targets=cd7dfdc4-003d-4ab0-a879-02abdf43e94a.cfargotunnel.com"
  - "--force-default-targets"

sources:
  - gateway-httproute

provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-external-dns
        key: CF_API_TOKEN
