apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: techgarden

helmGlobals:
  chartHome: ../../../../../helm-charts

helmCharts:
  - name: generic-service
    releaseName: sprout-ui
    valuesFile: ../../base/values.yaml
    namespace: techgarden
    additionalValuesFiles:
      - values.yaml
